repaygithub/ui-tools

modules/repay-scripts/README.md
modules/repay-scripts/package.json
modules/repay-scripts/src/cli.js
modules/repay-scripts/src/commands/build.js
modules/repay-scripts/src/commands/dev.js
modules/repay-scripts/src/configs/rollup.js

Adds the ability to have config files for libraries
fixes #4

Adds config option for libraries

---

modules/repay-scripts/src/commands/dev.js
yarn.lock

fixes #7
Adds custom logging output for webpack dev server instead of the default which is mostly just noisy. The full logs can still be viewed with the `--debug` option.

feat(repay-scripts): improve web app logging

---

modules/eslint-config/index.js

This rule is a nice safety net to catch you when you forget to import `React` into a JSX file

Add react/react-in-jsx-scope to eslint-config

---

modules/repay-scripts/package.json
yarn.lock

Upgraded `@repay/babel-preset` in `repay-scripts` so we'd have access to dynamic import syntax and published v0.2.2

chore(repay-scripts): Upgrade @repay/babel-preset & publish v0.2.2

---

modules/repay-scripts/package.json
modules/repay-scripts/src/configs/rollup.js
package.json
yarn.lock

Also, upgrades dependencies and includes a fix to enable upgrading to `@repay/babel-preset@v0.3.0`

fix(repay-scripts): consider nested resource as external

---

.prettierignore
.prettierrc
modules/repay-scripts/src/configs/web.js
package.json
tsconfig.json
yarn.lock

Ticket: https://repayonline.atlassian.net/browse/CACTUS-230
This is a prereq for getting the IE tests.  Basically consumers of `@repay/cactus-i18n` will always need to manually configure Webpack to transpile all `@fluent` modules in order to get their application to work on IE.  To make this easier, we'd like to bake this into the default `repay-scripts` Webpack config.
The best way to test would be to pull this down, link it to Cactus, and then try to build one of the `examples` modules.  You might want to add a log statement to the `build.js` file just to make sure you're linking correctly 😄

CACTUS-230 :: Transpile Fluent by default

---

modules/repay-scripts/src/commands/build.js

As I was working on [this](https://repayonline.atlassian.net/browse/CACTUS-256) ticket, I was having issues with the build and realized it's because we have to have an async webpack config function in the SSO theme. I added `await` before we call the config function which seemed to fix the issue (tested it with the linked package). This also shouldn't be a problem for configs that aren't async, as `await`ing a non-async function in JS is acceptable.
1. Check out this branch, add a log statement somewhere in `build.js` to make sure you're using the linked package, and run `yarn link` in the `repay-scripts` folder.
2. In the cactus repo, run `yarn link @repay/scripts` at the root.
3. Navigate to `examples/theme-components` & run `yarn build`
4. Make sure you were able to see your log …

fix(repay-scripts): Await the webpack config call in case it's async

---

.prettierignore
.prettierrc
modules/eslint-config/gateway-example.js
modules/eslint-config/package.json
modules/eslint-config/repay-api-example.js
modules/repay-scripts/src/cli.js
modules/repay-scripts/src/commands/build.js
modules/repay-scripts/src/commands/dev.js
modules/repay-scripts/src/configs/rollup.js
modules/repay-scripts/src/helpers/babelTranspiler.js
modules/repay-scripts/src/helpers/logger.js
modules/repay-scripts/tests/repay-scripts-build/react-application.test.js
modules/repay-scripts/tests/repay-scripts-build/react-library.test.js
modules/repay-scripts/tests/repay-scripts-build/web-application.test.js
modules/repay-scripts/tests/repay-scripts-dev/react-application.test.js
modules/repay-scripts/tests/repay-scripts-dev/react-library.test.js
modules/repay-scripts/tests/repay-scripts-dev/web-application.test.js
modules/repay-scripts/tests/static-server.js
modules/repay-scripts/tests/test-setup.js
package.json
yarn.lock

v2 of Prettier includes a few syntax changes that we should probably start including.  Plus a few
repos have pulled it in already, so we should probably start to standardize.
Pull down this branch, run `yarn install`, and then link this module to another repo (like Cactus).  Make sure that linting still works in your editor and in the command line.  One thing you should notice is that single-argument arrow functions now require parens, so you should see that change highlighted in existing files.

Upgrade Prettier to v2

---

modules/repay-scripts/src/cli.js
modules/repay-scripts/src/commands/build.js
modules/repay-scripts/src/commands/dev.js
modules/repay-scripts/src/configs/web.js
modules/repay-scripts/src/repay-scripts.js

Ticket: https://repayonline.atlassian.net/browse/CACTUS-271
This doesn't contribute directly to the ticket.  Instead, it adds some features that help the SSO Image use `repay-scripts`.  These include:
* Adding a `--watch` option to the `build` command.  `dev` doesn't apply for the SSO image, since it doesn't use webpack dev server.
* Fix a couple of bugs with the CSS/Style Loaders
* Add the ability to use async config functions with the `dev` command.  (I guess this doesn't really help the SSO image, since it doesn't use `dev`.  I made this change when I initially thought it could, and it seems useful enough to keep).
* Pull down this branch and link it to an app that uses `@repay/scripts` (like the Cactus example apps).  Run `yarn build` to make sure that works normally.  Run `yarn build …

CACTUS-271 :: Repay Scripts Improvements

---

README.md
modules/testing-tools/README.md
modules/testing-tools/package.json
modules/testing-tools/src/build-timed-test.js
modules/testing-tools/src/index.js
modules/testing-tools/src/utils/convert-milliseconds.js
modules/testing-tools/tests/build-timed-test.test.js
modules/testing-tools/tests/convert-milliseconds.test.js
yarn.lock

Ticket: https://repayonline.atlassian.net/browse/CACTUS-269
Making tests for this was a huge pain. Both Jest and TestCafe have a global `test` variable, so at the time that tests are running, the `test` that is referenced when building the timed testcafe test is actually a reference to Jest's `test`. 🤦‍♂️ To get around this, I had to try to mock the `test` from TestCafe. Unfortunately, I didn't know how to do that effectively, which limits our testing capability here. For example, I can't `await` the test function being called in the mock, so I can't check anything that was logged to the console. If anyone has any ideas for how I could improve the mock, that'd be awesome. Who knows, maybe that'd help me figure out how to do this with function chaining.
EDIT: Credit & thank you to …

CACTUS-269 :: Timed ETE Tests

---

modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t
modules/eslint-config/.prettierrc.template
modules/eslint-config/cli.js
modules/eslint-config/package.json
package.json
yarn.lock

https://repayonline.atlassian.net/browse/CACTUS-283
The first change can easily be tested here or in cactus. The second change seems kind of unrelated, but is still mentioned on the ticket; I also have no idea how to test it.
Another thing I'm not sure of: in the cactus repo changes for this ticket, there was a change in `.eslintrc`, changing the `parser` from `typescript-eslint-parser` to `@typescript-eslint/parser`. It seems like this change isn't necessary here, but I don't know why.

CACTUS-283 Upgrade eslint

---

modules/babel-preset/README.md
modules/babel-preset/index.js
modules/babel-preset/package.json
modules/repay-scripts/package.json
modules/repay-scripts/src/configs/babel.js
modules/repay-scripts/src/configs/web.js
yarn.lock

Ticket: https://repayonline.atlassian.net/browse/CACTUS-300
Previously we weren't adding any polyfills with `@repay/scripts`.  Given that we support IE11, that's bad.  This PR adds them in.  We had to manually add them in for the CoreJS features, as Babel's `usage` polyfill option didn't seem to properly detect the necessary polyfills for the Fluent library.  For the regenerator polyfill, however, Babel's automatic option worked just fine.
1. Run `yarn` to install the new dependencies
2. Run `yarn link` inside `modules/babel-preset`
3. Run `yarn link` inside `modules/repay-scripts`
4. Go over to Cactus and run `yarn link @repay/babel-preset`, followed by `yarn link @repay/scripts`
5. Run `yarn w standard start`
6. Open up the app in IE11 in BrowserStack to make sure that it loads/works

CACTUS-300 :: Add polyfills to REPAY scripts

---

modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t

Just want to make sure we keep up-to-date with the newly released `@repay/scripts` and `@repay/eslint-config`.  To test, ensure that `create-repay-ui`, that `yarn why @repay/scripts` spits out v2.0.0 inside your generated project folder, and that `yarn why @repay/eslint-config` spits out v3.0.0.

Upgrade @repay/scripts and @repay/eslint-config in @repay/create-ui

---

modules/create-repay-ui/package.json

Ticket: https://repayonline.atlassian.net/browse/CACTUS-318
Testing is a bit hard, because this bug didn't show up using a linked package.  But you could do the following.
1. `cd` into `./modules/create-repay-ui`
2. Run `yalc publish` (if you have yalc https://www.npmjs.com/package/yalc)
3. Run `yarn global add ~/.yalc/packages/@repay/create-ui/0.0.2`
4. Run `create-repay-ui` and make sure that it works

CACTUS-318 :: add _templates folder to published package for @repay/create-ui

---

modules/eslint-config/README.md
modules/eslint-config/package.json
modules/eslint-config/ts.js
yarn.lock

Ticket: https://repayonline.atlassian.net/browse/CACTUS-281
This is my first time ever setting up an eslint config, so please let me know if there's anything I'm doing here that's just outright wrong. I kind of just fiddled around until I was able to get something working so 🤷 
I copied the rules from the JS config into the TS one because I figured we still probably want to enforce those, but I'm open to suggestions if there's anything anyone would like to change there.
I recommend using a tool like Yalc (https://www.npmjs.com/package/yalc) to test this.
1. Check out this branch and run `yarn install`
2. Run `yalc publish` in `modules/eslint-config`
3. In cactus, run `yalc add --dev @repay/eslint-config`
4. In `package.json` at the root of cactus, add `.yalc/*` and `.yalc/@*/*` to the …

CACTUS-281 :: TypeScript Linting

---

yarn.lock

Quick `yarn.lock` update to fix a dependapot alert.
1. Pull this down, `cd ./modules/repay-scripts` and run `yalc publish`
2. Use `create-repay-ui` to generate a new application.
3. In the generated application, run `yalc add --dev @repay/scripts`.
4. Run `yarn` to reinstall everything.
5. Make sure `yarn start` and `yarn build` still work correctly.
(You can also test this in a Cactus example app if you'd rather do that.)

Upgrade terser-webpack-plugin and serialize-javascript

---

modules/create-repay-ui/_templates/templates/javascript/home.ejs.t
modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/shared/app.ejs.t
modules/create-repay-ui/_templates/templates/shared/loading.ejs.t
modules/create-repay-ui/_templates/templates/typescript/home.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t

Ticket: https://repayonline.atlassian.net/browse/CACTUS-322
Mostly just fixing some issues with the dependencies (i.e. missing peer dependencies and dev dependencies that should be regular dependencies) and making use of some Cactus components on the Home page.
1. `cd ./modules/create-repay-ui` and run `yalc publish`
2. Go to some other folder.  Run `yarn global add ~/.yalc/packages/@repay/create-ui/0.0.3`
3. Run `create-repay-ui testing`.  Select JS or TS and create an app
4. `cd` into your generated app.  Make sure `yarn test`, `yarn lint`, and `yarn test:types` (if applicable) all work.
5. Run `yarn start` to run the app.  Make sure everything looks good.

create-repay-ui updates

---

yarn.lock

This should only affect webpack in `@repay/scripts`, so if you want to test this, make sure you can still use `@repay/scripts` to build, etc.  (I'd recommend creating an app with the `create-repa-ui` CLI and then using `yalc` to swap out `@repay/scripts` for your local version.)

Upgrade bl library to address security vulnerability

---

modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t

1. Pull down branch.
2. `cd` into `modules/create-repay-ui` and run `yalc publish`
3. Run `yarn global add ~/.yalc/packages/@repay/create-ui/0.1.0` to install the executable from the yalc version
4. Run `create-repay-ui` twice...once for JS and once for TS.  Ensure that `@repay/cactus-web` is on v2.0.0 for both versions.
5. Check that the app runs okay with `yarn start`.

Upgrade @repay/cactus-web to v2

---

.gitignore
modules/testing-tools/package.json
package.json
yarn.lock

Ticket: https://repayonline.atlassian.net/browse/CACTUS-291
This is essentially the same thing as https://github.com/repaygithub/cactus/pull/418.  The difference is that I only included one package.  Unit tests don't really make sense for `babel-preset`, `create-repay-ui`, and `eslint-config`, while the tests for `repay-scripts` actually run the tool using `yarn`, so it doesn't actually register test coverage.  Maybe we can find a way to analyze coverage for that package later, but now is not that time.
So that means that only `testing-tools` is really getting analyzed here.  As with the Cactus version, I would just go to the ui-tools project in SonarQube and make sure that coverage is correctly captured. See https://sonarqube.repay.ninja/dashboard?id=ui-tools (you need to be on the VPN)

CACTUS-291 :: Add coverage support for SonarQube

---

package.json
scripts/blackduck.sh

Ticket: https://repayonline.atlassian.net/browse/CACTUS-292
This is PR number two for BlackDuck. It's pretty much exactly the same as the cactus PR.
If you want to test, you can trigger the Jenkins job [here](https://jenkins.internal.repay.ninja/blue/organizations/jenkins/ui-blackduck/activity) and you can view the project and the scan results [here](https://repay.blackducksoftware.com/api/projects/46268be4-1568-41d5-b8cb-2095e7956189/versions/1e219621-38d4-4c3b-b945-a27c5e34b1d3/components?sort=projectName%20ASC&offset=0&limit=100&filter=bomInclusion%3Afalse&filter=bomMatchReviewStatus%3AREVIEWED). You will have to be on the VPN to access those links.

CACTUS-292 :: BlackDuck Setup

---

modules/create-repay-ui/_templates/templates/javascript/layout.ejs.t
modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/typescript/layout.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t

Generate a new app. Check that the generated code has the latest cactus packages and that the BrandBar braking change has been addressed
[CACTUS-453]
[CACTUS-453]: https://repayonline.atlassian.net/browse/CACTUS-453

chore(create-repay-ui): upgrade cactus packages and fix braking changes

---

modules/create-repay-ui/_templates/templates/shared/example-test.ejs.t

The unit test file was in a separate directory from the test setup (we had two separate `tests` directories).  This fixes that.
1. Pull this down, `cd` into `modules/create-repay-ui`, and run `yalc publish`.
2. Run `yarn global add ~/.yalc/packages/@repay/create-ui/0.4.2`
3. Run `create-repay-ui test-app`.  You can choose JS, TS, or do both.
4. `cd` into the generated app, and make sure that `yarn test` runs without any errors.

Fix create-repay-ui test directory structure

---

modules/babel-preset/index.js
modules/babel-preset/package.json
yarn.lock

Installing and testing the `babel plugin styled-components` to enhance debugging and bundle size.
[CACTUS-279](https://repayonline.atlassian.net/browse/CACTUS-279)
Following the documentation related to the babel-plugin-styled-components, I decided to divide what I’ve found after installing the plugin into our UI-tools into the different features offered by this plugin. Please let me know if there is something I’m missing. 
Server-side rendering
Thought that we don’t need this enabled, so I decided to disabled this option.
Better debugging
By doing a quick inspection of the DOM elements with the browser’s devTools,  you could notice that the classes of the elements now have interesting prefixes that show to us the name of the components. I think this is an interesting feature, now we have …

CACTUS-279: babel-plugin-styled-components

---

modules/create-repay-ui/_templates/templates/javascript/packagejson.ejs.t
modules/create-repay-ui/_templates/templates/typescript/packagejson.ejs.t

@repay/cactus-web and @repay/eslint-config were been upgraded to 6.0.0 and 5.0.0 respectively
[CACTUS-543](https://repayonline.atlassian.net/browse/CACTUS-543)
Not sure if there is something I have to do to complete this ticket, please let me know in that case!

CACTUS-543: dependency upgrade

---

package.json
yarn.lock

I shouldn't have deleted that.  I assumed it was a dependency of `@repay/internal-release` for some reason, but it's really not.  It's a peer dependency (in my dependency ticket for `ui-private`, I'll make sure it's marked as such).
This _probably_ works, but it's hard to be 100% sure without running the full release script, which obviously I don't want to do yet.

CACTUS-617 :: Add Lerna back in

---

.circleci/config.yml

Much like in Cactus, we're running into problems after node changing their LTS version to 16.  For now, lets just downgrade to v14.  I've created three tech debt tickets in our backlog to allow us to spend time upgrading/fixing tests in each of our repos.

Temporarily downgrade node to v14 in CI to fix tests

---

modules/eslint-config/package.json
yarn.lock

Some eslint packages that are needed for linting TS projects were removed from `eslint-config`. This adds them back.

fix(eslint-config): add TS eslint packages back

---

modules/testing-tools/package.json
yarn.lock

https://repayonline.atlassian.net/browse/CACTUS-811
1. Pull down this branch and run `yarn install`
2. `cd modules/testing-tools` and `yalc publish`
3. Go to the cactus repo, `cd examples/standard`, `yalc add --dev @repay/testing-tools`, `yarn install` and run `yarn test:ci` to make sure the tests run & pass

CACTUS-811 :: Add `testcafe-browser-provider-browserstack` back to testing-tools

---

.circleci/config.yml
modules/testing-tools/package.json
modules/testing-tools/tests/build-timed-test.test.js
modules/testing-tools/tests/setup.js

https://repayonline.atlassian.net/browse/CACTUS-776
Would've been easier to start using the global `performance` object since it exists globally now, but I didn't want to have to restrict our users to node >= 16.

CACTUS-776 :: Upgrade node in CI

---

modules/babel-preset/index.js

[CACTUS-813](https://repayonline.atlassian.net/browse/CACTUS-813)
Testing: 
- `cd modules/babel-preset `
- Run `yalc publish`
- Go to cactus repo and run `yalc add --dev @repay/babel-preset`
- Run `yarn install`, `yarn cleanup`, `yarn build` and make sure the warning is not present anymore
- Run `yarn test:ci` and make sure the warning is gone.

CACTUS-813 :: Silence warning 

---

modules/repay-scripts/src/configs/rollup.js

https://repayonline.atlassian.net/browse/CACTUS-870
I suggest testing it in two different cases.
1. `cd` to `modules/repay-scripts` and run `yalc publish`.
2. Use [this branch](https://github.com/repaygithub/ui-private/compare/cactus-870-uat). `cd` to `ui-private/modules/internal-components`. Before adding the updated module, try running `yarn build`; you should get an error.
3. Run `yalc add @repay/scripts`, then from the `ui-private` root run `yarn install`. Back in the `internal-components` directory, run `yarn build` again, and this time it should work.
The second case is `cactus-web`, but because of the ongoing dependency weirdness there, you can't just use `yalc`. Instead, just modify `cactus/node_modules/@repay/scripts/src/config/rollup.js` with the same change you see in this PR, …

CACTUS-870: change rollup config to work in more cases

---

yarn.lock

https://repayonline.atlassian.net/browse/CACTUS-1091
Both `decode-uri-component` and `loader-utils` had security vulnerabilities.
The issue with `decode-uri-component` was fixed in version 0.2.2 and the issue with `loader-utils` was fixed in versions 1.4.1 and 2.0.3.

CACTUS-1091 :: Security Updates
